language: go
go:
  - "1.10.x"

before_deploy:
  - GOOS=openbsd GOARCH=amd64 go build -o pdericson github.com/pdericson/pdericson/cmd/pdericson
  - openssl aes-256-cbc -K $encrypted_88142569f400_key -iv $encrypted_88142569f400_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d && chmod 600 ~/.ssh/id_rsa

deploy:
- provider: script
  script: "set -x; ssh -o BatchMode=yes -o StrictHostKeyChecking=no -o User=deploy pdericson.com mkdir -p bin && scp -o BatchMode=yes -o StrictHostKeyChecking=no -o User=deploy pdericson pdericson.com:bin/"
  skip_cleanup: true
  on:
    branch: master
