language: go
go:
  - "1.10.x"

before_deploy:
  - go get -u github.com/go-swagger/go-swagger/cmd/swagger
  - swagger generate spec -o ./cmd/pdericson/static/swagger.json -b github.com/pdericson/pdericson/cmd/pdericson
  - go get -u github.com/gobuffalo/packr/...
  - packr
  - CGO_ENABLED=1 GOOS=openbsd GOARCH=amd64 go build -ldflags "-X main.version=$TRAVIS_COMMIT" -o pdericson github.com/pdericson/pdericson/cmd/pdericson
  - packr clean
  - openssl aes-256-cbc -K $encrypted_88142569f400_key -iv $encrypted_88142569f400_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d && chmod 600 ~/.ssh/id_rsa

deploy:
- provider: script
  script: sh .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master
